### PR TITLE
fix: copy issues, compile target, trace app, add overwrite and debug option

### PR DESCRIPTION
**Pull request by nickofthyme**
This adds the following:

- Set transpilation target to `node12`
- Copies the `trace/` app to the final merged report only if any of the original reports contain it. All trace `.zip` test files were already being copied correctly.
- Adds `debug` option to allow user to control verbosity. (default: `false`)
- Adds `overwriteExisting` option to control overwriting existing report. (default: `true`)
- Fixes error with `contentFolderPath` when copying `data/`, it was not joining the src and filename path correctly. See code line diff [here](https://github.com/anooprav7/playwright-merge-html-reports/pull/6/files#diff-d5704acc519fb6bfc0ec58d7dff89dc373f4101080cf74de7df11849e9415ed7L129).

> ⚠️ Waiting on confirmation of other issues to remove merged report and dist files from PR.

### CODE REVIEW

**Comment by nickofthyme** [comment]
@mstepin regarding https://github.com/anooprav7/playwright-merge-html-reports/pull/3#issuecomment-1157107786 I changed the target to `node12`. You can test this out with the same link defined in https://github.com/anooprav7/playwright-merge-html-reports/pull/6#issuecomment-1157944546. Note the changes to `dist/` files in https://github.com/anooprav7/playwright-merge-html-reports/pull/6/commits/3f86cc47cb2b9bc03159c280763233c29ca1cf3c now transpile the `??` syntax.

**Comment by mstepin** [comment]
Thanks. Works in my tests. Will this be merged to the master version soon?

**Comment by nickofthyme** [comment]
Not sure, @mrmckeb have you had a chance to test this?

**Comment by mrmckeb** [comment]
Thanks, I've tested this today and it's working well for us too - we have two different sets of reports, and I've tested with both.

**Comment by nickofthyme** [comment]
Nice! @anooprav7 Could you test this and merge when you get a chance? I removed the build files but you should be able to still test it pointing to 3f86cc47cb2b9bc03159c280763233c29ca1cf3c, something like...

```jsonc
// package.json
{
  "dependencies": {
    "@playwright/test": "^1.21.1",
    "playwright-merge-html-reports": "nickofthyme/playwright-merge-html-reports#3f86cc47cb2b9bc03159c280763233c29ca1cf3c"
  } 
}
```

**Comment by anooprav7** [comment]
Release log - https://github.com/anooprav7/playwright-merge-html-reports/releases/tag/v0.2.4
Published - https://www.npmjs.com/package/playwright-merge-html-reports/v/0.2.4

**Comment by mrmckeb** [comment]
I'm not sure what happened, but I'm now able to reproduce the `index.html` issue again with `0.2.4`.

@anooprav7 @nickofthyme to reproduce:
1. I have two reports in two folders:
  - `report-1`
  - `report-2`
2. I run:
  ```js
await mergeHTMLReports(paths, {
  outputFolderName: `playwright-combined-report`,
});
   ```
3. I get error: `[Error: ENOENT: no such file or directory, open '[...dir]/playwright-combined-report/index.html']`

**Comment by nickofthyme** [comment]
@mrmckeb can you share these two reports so I can test against them directly? Cuz I cannot reproduce this issue on the current example reports.

**Pull request merged**
